
steps:
- task: AzureWebAppContainer@1
  inputs:
    azureSubscription: 'Bayan Allouzi (48c2ece5-ded8-4806-8c46-72df34f73606)'
    appName: 'mypython-customcontainer'
    containers: 'ACRCustomRegistry1213.azurecr.io/samples/nginx:v2'
    configurationStrings: '-Port 5000 -RequestTimeout 5000 -new_settings devops_deployment_test'