
steps:
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Bayan Allouzi (48c2ece5-ded8-4806-8c46-72df34f73606)'
    appType: 'webAppContainer'
    WebAppName: 'mypython-customcontainer'
    DockerNamespace: 'ACRCustomRegistry1213.azurecr.io'
    DockerRepository: 'helloacrtasks'
    DockerImageTag: 'v1'
    AppSettings: 'bayan:bayan'